</div>
<!--BT引入JS-->
<script type="text/javascript" language="JavaScript" src="<?php echo yii\helpers\Url::base(true);?>/js/bootstrap.js"></script>
<script type="text/javascript" language="JavaScript" src="<?php echo yii\helpers\Url::base(true);?>/js/mtywl.js"></script>
<script type="text/javascript" language="JavaScript" src="<?php echo yii\helpers\Url::base(true);?>/js/country.js"></script>
<!--BT的JSEND-->
</body>
<?php echo $this->endBody();?>
</html>
<?php echo $this->endPage();?>