<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/13 0013
 * Time: 上午 10:57
 */

namespace app\modules\systems\models;


use yii\db\Query;

class EbayAccount extends SystemsModel
{
    public static function tableName()
    {
        return '{{%system}}.{{%ebay_account}}'; // TODO: Change the autogenerated stub
    }

    public static function getIdNameKVList()
    {
        return array_column(self::find()->select('id,user_name')->orderBy('user_name')->asArray()->all(),'user_name','id');
    }

    public static function getNameById($id)
    {
        return self::find()->select('user_name')->where(['id'=>$id])->asArray()->one()['user_name'];
    }

}