<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/29 0029
 * Time: 上午 9:38
 */

namespace app\modules\mails\models;


class EbayFeedbackResponse extends MailsModel
{
    public static $responseTypeMap = [1=>'FollowUp',2=>'Reply'];
    public static function tableName()
    {
        return '{{%ebay_feedback_response}}'; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'feedback_id'                               => '评价ID',
            'item_id'                                   => 'ItemID',
            'order_line_item_id'                        => '产品订单ID',
            'response_text'                             => '内容',
            'response_type'                             => '类型',
            'target_user_id'                            => '用户',
            'transaction_id'                            => '交易ID',
            'account_id'                                => 'eBay账号',
            'siteid'                                    => '站点',
            'create_by'                                 => '创建者',
            'create_time'                               => '创建时间',
            'modify_by'                                 => '修改者',
            'modify_time'                               => '修改时间',
        ];
    }
    public function rules()
    {
        return [
            [['response_text','feedback_id','response_type','target_user_id'],'required'],
            ['response_text','string','length'=>[1,125]],
            [['item_id','transaction_id'],'string','max'=>19],
            ['order_line_item_id','string','max'=>50],
            ['response_type','checkResponseType'],
            ['account_id','integer','min'=>1],
            ['siteid','integer']
        ];
    }

    public function checkResponseType($attribute)
    {
        if(is_numeric($this->$attribute))
        {
            if(!isset(self::$responseTypeMap[$this->$attribute]))
                $this->addError($attribute,'值错误');
        }
        else
        {
            $value = array_search($this->$attribute,self::$responseTypeMap);
            if($value === false)
                $this->addError($attribute,'值错误');
            else
                $this->$attribute = $value;
        }
    }

}