<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/20 0020
 * Time: 上午 10:03
 */

namespace app\modules\mails\models;


class EbayCaseResponse extends MailsModel
{
    public static function tableName()
    {
        return '{{%ebay_case_response}}'; // TODO: Change the autogenerated stub
    }
}