<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/13 0013
 * Time: 上午 10:37
 */

namespace app\modules\products\models;


class EbaySiteMapAccount extends ProductsModel
{
    public static function tableName()
    {
        return '{{%ebay_site_map_account}}'; // TODO: Change the autogenerated stub
    }
}