<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/27 0027
 * Time: 下午 7:24
 */

namespace app\modules\products\models;


class EbaySites extends ProductsModel
{
     public static function tableName()
     {
         return '{{%ebay_sites}}'; // TODO: Change the autogenerated stub
     }
}