<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/20 0020
 * Time: 下午 1:54
 */

namespace app\modules\products\models;


class EbayListing extends ProductsModel
{
    public static function tableName()
    {
        return '{{%ebay_listing}}'; // TODO: Change the autogenerated stub
    }
}