<?php
/**
 * Created by PhpStorm.
 * User: zhangchu
 * Date: 2018/12/01 
 */

namespace app\modules\products\models;

use app\common\MHelper;

class ProductTask extends ProductsModel
{
     public static function tableName()
     {
         return '{{%product_task}}'; // TODO: Change the autogenerated stub
     }

    /**
     * 根据sku获取质检员
     * @param  [string] $sku 
     * @return [string] $qualityernam    
     */
     public static function getSkuByQualityer($sku){
         $row = self::find()
                 ->select('id,qualityer')
                 ->from(self::tableName())   
                 ->where("sku='{$sku}'")
                 ->asArray()
                 ->one();
         $qualityer = $row['qualityer'];
         $qualityername = "";
         if(!empty($qualityer)){
             $qualityername = MHelper::getUsername($qualityer);
         }
         return $qualityername;
     }
}
