<?php
namespace app\modules\orders\models;
use app\components\Model;

class CancelTransaction extends Model
{
    public static function tableName()
    {
        return '{{%ebay_cancel_transaction}}'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
    	return [
    		[['status','reason','account_id'],'required']
    	];
    }
}