<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/19 0019
 * Time: 下午 3:56
 */

namespace app\modules\orders\models;
use Yii;
class OrderReplyQuery extends OrderModel
{
    const SEND_FAIL = -1;
    const IS_NOT_SEND = 0;
    const IS_SEND = 1;
    const NOT_TO_SEND = 2;
    const SEND_FAULT = 0;

    const MAX_FAIL_COUNT = 5;
    public static function tableName()
    {
        return '{{%order_reply_query_list}}'; // TODO: Change the autogenerated stub
    }
}